name: Mirror official Langflow image to Docker Hub

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull official Langflow
        run: docker pull ghcr.io/langflow/langflow:latest

      - name: Tag for Docker Hub
        run: docker tag ghcr.io/langflow/langflow:latest deeprat/trueeye-flow-base:latest

      - name: Push to Docker Hub
        run: docker push deeprat/trueeye-flow-base:latest
