name: Mirror LangFlow to GHCR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  packages: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull official LangFlow
        run: docker pull langflowai/langflow:latest

      - name: Tag & push to GHCR
        run: |
          docker tag langflowai/langflow:latest \
            ghcr.io/${{ toLower(github.repository_owner) }}/trueeye-flow-base:latest

          docker push ghcr.io/${{ toLower(github.repository_owner) }}/trueeye-flow-base:latest

      - name: Verify it’s there
        run: docker pull ghcr.io/${{ toLower(github.repository_owner) }}/trueeye-flow-base:latest
